#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

int threshold = 15;


int limit(int input, int min, int max)
{
	if(input < min)
	{
		return min;
	}
	if(input > max)
	{
		return max;
	}
	return input;
}
void powLeft(int power)
{
	power = limit(power, 0, 100);
	motor[motorD]=power;
	motor[motorE]=power;
}
void powRight(int power)
{
	power = limit(power, 0, 100);
	motor[motorF] = power;
	motor[motorG] = power;
}

void initializeRobot()
{
	servo[servo1] = 0;
	servo[servo2] = 0;
}

void iterate()
{
	getJoystickSettings(joystick);
	//Main Drive
	int left = joystick.joy1_y1 / 1.28;
	int right = joystick.joy1_y2 / 1.28;
	if(left<threshold)
	{
		left = 0;
	}
	if(right < threshold)
	{
		right = 0;
	}
	powLeft(left);
	powRight(right);

	//Secondary Functions
	if(joy1Btn(1))
	{
		servo[servo1] = 0;
		//servo[servo2] = 0;
	}
	if(joy1Btn(2))
	{
		servo[servo1] = 60;
		//servo[servo2] = 127;
	}

}

task main()
{
	initializeRobot();
	while(true)
	{
		iterate();
		wait1Msec(50);
	}
}
